export const OPERATOR = 'operator';
export const BOOLEAN = 'bool';
export const ERROR = 'error';
export const NUMBER = 'number';
export const FUNCTION = 'func';
export const NEWLINE = 'newline';
export const WHITESPACE = 'whitespace';
export const STRING = 'string';
export const CONTEXT_QUOTE = 'context_quote';
export const CONTEXT = 'context';
export const RANGE = 'range';
export const RANGE_BEAM = 'range_beam';
export const RANGE_TERNARY = 'range_ternary';
export const RANGE_NAMED = 'range_named';
export const FX_PREFIX = 'fx_prefix';
export const UNKNOWN = 'unknown';

export const MAX_COLS = 2 ** 14 - 1; // 16383
export const MAX_ROWS = 2 ** 20 - 1; // 1048575
