export const OPERATOR = 'operator';
export const BOOLEAN = 'bool';
export const ERROR = 'error';
export const NUMBER = 'number';
export const FUNCTION = 'function';
export const NEWLINE = 'newline';
export const WHITESPACE = 'whitespace';
export const STRING = 'string';
export const PATH_QUOTE = 'path-quote';
export const PATH_BRACE = 'path-brace';
export const PATH_PREFIX = 'path-prefix';
export const RANGE = 'range';
export const RANGE_BEAM = 'range-beam';
export const RANGE_NAMED = 'range-named';
export const FX_PREFIX = 'fx-prefix';
export const UNKNOWN = 'unknown';

export const MAX_COLS = 2 ** 14 - 1; // 16383
export const MAX_ROWS = 2 ** 20 - 1; // 1048575
